### ISSUE TITLE
Score: Letzte Ziffer schwer lesbar

### ISSUE THREAD

**Issue by kinnla** [wassermann-projekt/wassermann#45]
PRECONDITION: Das Spiel läuft
ACTION: Spiele so lange, bis der Score dreistellig wird
ACTUAL BEHAVIOR: Der Hintergrund der letzten Ziffer ist zur Hälfte schwarz, so dass die Ziffern schwer lesbar sind (siehe Screenshot)
EXPECTED BEHAVIOR: Alle Ziffern sind gut lesbar
![image](https://cloud.githubusercontent.com/assets/3518808/13907112/446603bc-eee7-11e5-90b3-1b096661db7e.png)

**Comment by krawez** [comment]
geändert!
