### ISSUE TITLE
Hindernisgenerator unter Wasser generiert unmögliche Hindernisse

### ISSUE THREAD

**Issue by LuiseHenriette** [wassermann-projekt/wassermann#47]
PRECONDITION: Man ist im Unterwassermodus
ACTION: Versuche das Hindernis zu durchqueren
ACTUAL BEHAVIOR: Es entstehen Hinderniskonstellationen, die unmöglich zu überwinden sind
EXPECTED BEHAVIOR: Es ist möglich durch die generierten Hindernisse zu schwimme

**Comment by krawez** [comment]
gemacht!
