### ISSUE TITLE
Balancing: Anfangsgeschwindigkeit, Hindernisse

### ISSUE THREAD

**Issue by kinnla** [wassermann-projekt/wassermann#63]
Das Spiel ist heute viel schwerer als gestern, gut so! Die Anfangsgeschwindigkeit ist für meinen Geschmack etwas zu langsam. Dadurch ist es schwer, den Schwänen auszuweichen. Variante: das Spiel ist schon in Level 1 recht schnell, aber es gibt weniger Hindernisse.

**Comment by krawez** [comment]
danke, fixed :) Wir spielen mit der Geschwindigkeiten gerade noch...
