### ISSUE TITLE
Hindernisse verschwinden bei Unverwundbarkeit

### ISSUE THREAD

**Issue by mtilgner** [wassermann-projekt/wassermann#64]
PRECONDITION: Das Spiel läuft
ACTION: Kollidiere mit Hindernis, während Spieler unverwundbar ist (durch vorherige Kollision).
ACTUAL BEHAVIOR: Hindernis verschwindet
EXPECTED BEHAVIOR: Hindernis verschwindet nicht

**Comment by krawez** [comment]
gefixt!
