### ISSUE TITLE
Uhren werden nicht generiert

### ISSUE THREAD

**Issue by sqAree** [wassermann-projekt/wassermann#65]
PRECONDITION: Game is running, player enters level 7
ACTION: 
EXPECTED BEHAVIOUR: obstacle generator creates stopwatches with a probability of 5% per generated obstacle
ACTUAL BEHAVIOUR: no stopwatch is ever created
COMMENT: unknown reason

**Comment by krawez** [comment]
sqAree, hast du schon versucht die Wahrschenlichkeit auf höher zu setzten? Bei mir in der alten Version von der HIndernissgenerator die Uhren kommen...

**Comment by krawez** [comment]
Hab es getestet - Uhren kommen. Wenig, aber sie kommen.
